version: 2.0

jobs:
  build-ui:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: install build dependencies
          command: sudo apt install rsync

      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@8'

      - run:
          name: install dependencies
          command: npm ci

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run:
          name: check code format with lint
          command: npm run lint

      - run:
          name: jest tests
          command: npx jest

      - run:
          name: build
          command: npm run build

      - persist_to_workspace:
          root: ./
          paths:
            - lib

  deploy-docs:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - attach_workspace:
          at: ./

      - run:
          name: Install and configure docs dependencies
          command: |
            cd docs
            npm i
      - run:
          name: build docs
          command: |
            cd docs
            npm run build

      - run:
          name: Install and configure dependencies
          command: npm i

      - run:
          name: Disable jekyll builds
          command: touch docs/__DOCS__/dist/iroco-ui/.nojekyll

      - run:
          name: cp circleci config
          command: cp -a .circleci docs/__DOCS__/dist/iroco-ui/

      - add_ssh_keys:
          fingerprints:
            - '6d:0d:3c:48:0a:59:2a:0b:b8:3e:ad:95:2a:6a:7d:c6'

      - run:
          name: Deploy docs to gh-pages branch
          command: npx gh-pages --dotfiles --message "[ci skip] Updates" --dist docs/__DOCS__/dist/iroco-ui

workflows:
  version: 2
  build_workflow:
    jobs:
      - build-ui:
          filters:
            branches:
              only: main
      - deploy-docs:
          requires:
            - build-ui
          filters:
            branches:
              only: main
