version: 2.0

jobs:
  build_ui:
    docker:
      - image: circleci/node:14

    steps:
      - checkout

      - run:
          name: install build dependencies
          command: sudo apt install rsync

      - run:
          name: install dependencies
          command: yarn

      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - node_modules

      - run:
          name: jest tests
          command: npx jest

      - run:
          name: build
          command: yarn build

      - persist_to_workspace:
          root: project
          paths:
            - lib

  deploy-docs:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - attach_workspace:
         at: lib

      - run:
          name: Install and configure docs dependencies
          command: |
            cd docs
            yarn
      - run:
          name: build docs
          command: |
            cd docs
            yarn build

      - run:
          name: Install and configure dependencies
          command: yarn

      - run:
          name: Deploy docs to gh-pages branch
          command: npx gh-pages --dist docs/__DOCS__/dist/iroco-ui

workflows:
  version: 2
  build_workflow:
    jobs:
      - build_ui:
        filters:
          branches:
              only: master
      - deploy-docs:
          requires:
            - build
          filters:
            branches:
              only: master
